In [6]:
import pandas as pd
import numpy as np

data=pd.read_csv('./data/ames_prices.csv')
data.head()

,Order,PID,area,price,MS.SubClass,MS.Zoning,Lot.Frontage,Lot.Area,Street,Alley,...,Screen.Porch,Pool.Area,Pool.QC,Fence,Misc.Feature,Misc.Val,Mo.Sold,Yr.Sold,Sale.Type,Sale.Condition
0,1,526301100,1656,215000,20,RL,141.0,31770,Pave,NaN,...,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal
1,2,526350040,896,105000,20,RH,80.0,11622,Pave,NaN,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
2,3,526351010,1329,172000,20,RL,81.0,14267,Pave,NaN,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
3,4,526353030,2110,244000,20,RL,93.0,11160,Pave,NaN,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
4,5,527105010,1629,189900,60,RL,74.0,13830,Pave,NaN,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal

In [7]:
pd.set_option('display.max_rows', 100)
data.head().T

                         0          1          2          3          4
Order                    1          2          3          4          5
PID              526301100  526350040  526351010  526353030  527105010
area                  1656        896       1329       2110       1629
price               215000     105000     172000     244000     189900
MS.SubClass             20         20         20         20         60
MS.Zoning               RL         RH         RL         RL         RL
Lot.Frontage         141.0       80.0       81.0       93.0       74.0
Lot.Area             31770      11622      14267      11160      13830
Street                Pave       Pave       Pave       Pave       Pave
Alley                  NaN        NaN        NaN        NaN        NaN
Lot.Shape              IR1        Reg        IR1        Reg        IR1
Land.Contour           Lvl        Lvl        Lvl        Lvl        Lvl
Utilities           AllPub     AllPub     AllPub     AllPub     AllPub
Lot.Config          Corner     Inside     Corner     Corner     Inside
Land.Slope             Gtl        Gtl        Gtl        Gtl        Gtl
Neighborhood         NAmes      NAmes      NAmes      NAmes    Gilbert
Condition.1           Norm      Feedr       Norm       Norm       Norm
Condition.2           Norm       Norm       Norm       Norm       Norm
Bldg.Type             1Fam       1Fam       1Fam       1Fam       1Fam
House.Style         1Story     1Story     1Story     1Story     2Story
Overall.Qual             6          5          6          7          5
Overall.Cond             5          6          6          5          5
Year.Built            1960       1961       1958       1968       1997
Year.Remod.Add        1960       1961       1958       1968       1998
Roof.Style             Hip      Gable        Hip        Hip      Gable
Roof.Matl          CompShg    CompShg    CompShg    CompShg    CompShg
Exterior.1st       BrkFace    VinylSd    Wd Sdng    BrkFace    VinylSd
Exterior.2nd       Plywood    VinylSd    Wd Sdng    BrkFace    VinylSd
Mas.Vnr.Type         Stone        NaN    BrkFace        NaN        NaN
Mas.Vnr.Area         112.0        0.0      108.0        0.0        0.0
Exter.Qual              TA         TA         TA         Gd         TA
Exter.Cond              TA         TA         TA         TA         TA
Foundation          CBlock     CBlock     CBlock     CBlock      PConc
Bsmt.Qual               TA         TA         TA         TA         Gd
Bsmt.Cond               Gd         TA         TA         TA         TA
Bsmt.Exposure           Gd         No         No         No         No
BsmtFin.Type.1         BLQ        Rec        ALQ        ALQ        GLQ
BsmtFin.SF.1         639.0      468.0      923.0     1065.0      791.0
BsmtFin.Type.2         Unf        LwQ        Unf        Unf        Unf
BsmtFin.SF.2           0.0      144.0        0.0        0.0        0.0
Bsmt.Unf.SF          441.0      270.0      406.0     1045.0      137.0
Total.Bsmt.SF       1080.0      882.0     1329.0     2110.0      928.0
Heating               GasA       GasA       GasA       GasA       GasA
Heating.QC              Fa         TA         TA         Ex         Gd
Central.Air              Y          Y          Y          Y          Y
Electrical           SBrkr      SBrkr      SBrkr      SBrkr      SBrkr
X1st.Flr.SF           1656        896       1329       2110        928
X2nd.Flr.SF              0          0          0          0        701
Low.Qual.Fin.SF          0          0          0          0          0
Bsmt.Full.Bath         1.0        0.0        0.0        1.0        0.0
Bsmt.Half.Bath         0.0        0.0        0.0        0.0        0.0
Full.Bath                1          1          1          2          2
Half.Bath                0          0          1          1          1
Bedroom.AbvGr            3          2          3          3          3
Kitchen.AbvGr            1          1          1          1          1
Kitchen.Qual            TA         TA         Gd         Ex         TA
TotRms.AbvGrd            7          5          6          8          6
Functional             Typ        Typ        Typ        Typ        Typ
Fireplaces               2          0          0          2          1
Fireplace.Qu            Gd        NaN        NaN         TA         TA
Garage.Type         Attchd     Attchd     Attchd     Attchd     Attchd
Garage.Yr.Blt       1960.0     1961.0     1958.0     1968.0     1997.0
Garage.Finish          Fin        Unf        Unf        Fin        Fin
Garage.Cars            2.0        1.0        1.0        2.0        2.0
Garage.Area          528.0      730.0      312.0      522.0      482.0
Garage.Qual             TA         TA         TA         TA         TA
Garage.Cond             TA         TA         TA         TA         TA
Paved.Drive              P          Y          Y          Y          Y
Wood.Deck.SF           210        140        393          0        212
Open.Porch.SF           62          0         36          0         34
Enclosed.Porch           0          0          0          0          0
X3Ssn.Porch              0          0          0          0          0
Screen.Porch             0        120          0          0          0
Pool.Area                0          0          0          0          0
Pool.QC                NaN        NaN        NaN        NaN        NaN
Fence                  NaN      MnPrv        NaN        NaN      MnPrv
Misc.Feature           NaN        NaN       Gar2        NaN        NaN
Misc.Val                 0          0      12500          0          0
Mo.Sold                  5          6          6          4          3
Yr.Sold               2010       2010       2010       2010       2010
Sale.Type              WD         WD         WD         WD         WD
Sale.Condition      Normal     Normal     Normal     Normal     Normal

In [8]:
data['Central.Air']

0       Y
1       Y
2       Y
3       Y
4       Y
       ..
2925    Y
2926    Y
2927    Y
2928    Y
2929    Y
Name: Central.Air, Length: 2930, dtype: str

In [9]:
data['Central.Air']=np.where(data['Central.Air']=="Y",1,0)

In [10]:
data['Central.Air']

0       1
1       1
2       1
3       1
4       1
       ..
2925    1
2926    1
2927    1
2928    1
2929    1
Name: Central.Air, Length: 2930, dtype: int64

In [18]:
# Estimate propotion of central air=yes

sample_estimate=sum(data['Central.Air'])*(1/len(data))
sample_estimate

0.9331058020477816

## Part B

In [15]:
rng=np.random.default_rng(seed=51)
k=5000
ninv=1/len(data)

bootstrap_propotion=[]
for i in range(k):
    air=rng.choice(data['Central.Air'], size=len(data), replace=True)
    prop=sum(air)*ninv
    bootstrap_propotion.append(prop)

average_prop=round(np.mean(bootstrap_propotion),3)

print(f'After {k} bootstraped samples, the average proportion of central air is about {average_prop} with rng seed 51')

After 5000 bootstraped samples, the average proportion of central air is about 0.933 with rng seed 51

## Part C

In [17]:
bootstrap_standard_error=np.std(bootstrap_propotion, ddof=1)
bootstrap_standard_error

np.float64(0.0046454920596926)

## Part D

In [21]:
print(f'90% confidence interval [{sample_estimate-1.645*bootstrap_standard_error},{sample_estimate+1.645*bootstrap_standard_error}]')

print(f'95% confidence interval [{sample_estimate-1.96*bootstrap_standard_error},{sample_estimate+1.96*bootstrap_standard_error}]')

print(f'99% confidence interval [{sample_estimate-2.576*bootstrap_standard_error},{sample_estimate+2.576*bootstrap_standard_error}]')

90% confidence interval [0.9254639676095873,0.9407476364859759]
95% confidence interval [0.9240006376107841,0.9422109664847791]
99% confidence interval [0.9211390145020134,0.9450725895935498]

## Part E

$H_0:p=.9 \qquad \alpha=0.1,\quad 0.05,\quad 0.01$

At every level for $\alpha$, we reject the null hypothesis. In each  $(1-\alpha)$ confidence interval, .9 is outside of the interval, so there is enough statistically significant evidence to reject the null. Here, we can claim that the probability of having central air is larger than 90%

# Q8

In [2]:
transormed_area=np.arcsinh(data['area'])
transformed_price=np.arcsinh(data['price'])

In [36]:
sample_corr=np.corrcoef(transormed_area, transformed_price)
sample_corr[0][1]

np.float64(0.7231661530091357)

## Part a

In [32]:
rng=np.random.default_rng(seed=51)
k=5000
ninv=1/len(data)


bootstrap_corr=[]
for i in range(k):
    picked_index=rng.choice(range(len(data)), size=len(data), replace=True)
    bootstraped_price=transformed_price[picked_index]
    bootstrapped_area=transormed_area[picked_index]
    sample_bootstrap_corr=np.corrcoef(bootstraped_price,bootstrapped_area)
    bootstrap_corr.append(sample_bootstrap_corr[0][1])
    
corr_mean=np.mean(bootstrap_corr)

print(f'After {k} bootstraped samples, the average corr of transformed price and area is about {corr_mean} with rng seed 51')

After 5000 bootstraped samples, the average corr of transformed price and area is about 0.7231053640489304 with rng seed 51

## Part B

In [33]:
bootstrap_standard_error=np.std(bootstrap_corr, ddof=1)
bootstrap_standard_error

np.float64(0.01000723868469651)

## Part C

In [37]:
print(f'90% confidence interval [{sample_corr[0][1]-1.645*bootstrap_standard_error},{sample_corr[0][1]+1.645*bootstrap_standard_error}]')

print(f'95% confidence interval [{sample_corr[0][1]-1.96*bootstrap_standard_error},{sample_corr[0][1]+1.96*bootstrap_standard_error}]')

print(f'99% confidence interval [{sample_corr[0][1]-2.576*bootstrap_standard_error},{sample_corr[0][1]+2.576*bootstrap_standard_error}]')

90% confidence interval [0.70670424537281,0.7396280606454614]
95% confidence interval [0.7035519651871305,0.7427803408311409]
99% confidence interval [0.6973875061573575,0.7489447998609139]

## Part D

$H_0:\rho=0 \quad H_1:\rho\neq 0 \qquad \alpha=0.1,\quad 0.05,\quad 0.01$

At every level for $\alpha$, we reject the null hypothesis. In each  $(1-\alpha)$ confidence interval, 0 is outside of the interval, so there is enough statistically significant evidence to reject the null. Here, we can claim that there is a correlation between the area of a house and its price even though we had to transform our variables first.

## Part E

We had to keep the two variables paired because it would not make sense for us to calculate the correlation of two variables from two random different houses. The analysis only works because we are analyzing both the area and sales price of the same house.

# Q9

In [40]:
death=pd.read_csv('./data/metabric.csv')
death.head()

,Age at Diagnosis,Type of Breast Surgery,Cancer Type,Chemotherapy,Hormone Therapy,Lymph nodes examined positive,Mutation Count,Nottingham prognostic index,Overall Survival (Months),Overall Survival Status,Radio Therapy,TMB (nonsynonymous),Tumor Size,Tumor Stage
0,43.19,BREAST CONSERVING,Breast Cancer,NO,YES,0.0,2.0,4.020,84.633333,0:LIVING,YES,2.615035,10.0,1.0
1,48.87,MASTECTOMY,Breast Cancer,YES,YES,1.0,2.0,4.030,163.700000,1:DECEASED,NO,2.615035,15.0,2.0
2,47.68,MASTECTOMY,Breast Cancer,YES,YES,3.0,1.0,4.050,164.933333,0:LIVING,YES,1.307518,25.0,2.0
3,76.97,MASTECTOMY,Breast Cancer,YES,YES,8.0,2.0,6.080,41.366667,1:DECEASED,YES,2.615035,40.0,2.0
4,78.77,MASTECTOMY,Breast Cancer,NO,YES,0.0,4.0,4.062,7.800000,1:DECEASED,YES,5.230071,31.0,4.0

In [41]:
sample_survival=np.mean(death['Overall Survival (Months)'])
sample_survival

np.float64(129.09429138744105)

## Part a

In [43]:
rng=np.random.default_rng(seed=51)
k=5000
ninv=1/len(death)


bootstrap_survival=[]
for i in range(k):
    survival=rng.choice(death['Overall Survival (Months)'], size=len(death), replace=True)
    mean_survival=np.mean(survival)
    bootstrap_survival.append(mean_survival)
    
survival_average=round(np.mean(bootstrap_survival),3)


print(f'After {k} bootstraped samples, the average number of months for survival is about {survival_average} with rng seed 51')

After 5000 bootstraped samples, the average number of months for survival is about 129.121 with rng seed 51

## Part B

In [44]:
bootstrap_standard_error=np.std(bootstrap_survival, ddof=1)
bootstrap_standard_error

np.float64(2.1783832076860414)

## Part C

In [45]:
print(f'90% confidence interval [{sample_survival-1.645*bootstrap_standard_error},{sample_survival+1.645*bootstrap_standard_error}]')

print(f'95% confidence interval [{sample_survival-1.96*bootstrap_standard_error},{sample_survival+1.96*bootstrap_standard_error}]')

print(f'99% confidence interval [{sample_survival-2.576*bootstrap_standard_error},{sample_survival+2.576*bootstrap_standard_error}]')

90% confidence interval [125.51085101079751,132.6777317640846]
95% confidence interval [124.82466030037641,133.3639224745057]
99% confidence interval [123.48277624444181,134.7058065304403]

## Part D

$H_0:\mu=120 \quad H_1:\mu\neq 120 \qquad \alpha=0.1,\quad 0.05,\quad 0.01$

At every level for $\alpha$, we reject the null hypothesis. In each  $(1-\alpha)$ confidence interval, 120 is outside of the interval, so there is enough statistically significant evidence to reject the null. Here, we can claim the true value for average survival time is more than 120 months.

## Part E

We are 95% confident that the true value for survival months as time of death or last doctor's visit is captured in the range [124.8, 133.3] months. or [10.4, 11.1] years. Although, this is not an accurate measure of lifespan after treatment since one could have a final doctor's appointment months or even years before their eventual death and those months would not be accounted for with this data. We do know that this is at least not an overestimate since all patients were alive at least up to the recorded time.

# Q 10

## Part A

In [86]:
sleep=pd.read_csv('./data/nhanes_data_17_18.csv')
pd.set_option('display.max_rows', 200)
sleep.head().T

C:\Users\5maxc\AppData\Local\Temp\ipykernel_42848\1953053331.py:1: DtypeWarning: Columns (0: ServedActiveDutyInUsArmedForces) have mixed types. Specify dtype option on import or set low_memory=False.
  sleep=pd.read_csv('./data/nhanes_data_17_18.csv')

,0,1,2,3,4
SEQN,93703.0,93704.0,93705.0,93706.0,93707.0
GeneralHealthCondition,NaN,NaN,Good,Very good,Good
EverBreastfedOrFedBreastmilk,1.0,1.0,NaN,NaN,NaN
AgeStoppedBreastfeedingdays,273.0,60.0,NaN,NaN,NaN
AgeFirstFedFormuladays,1.0,3.0,NaN,NaN,NaN
AgeStoppedReceivingFormuladays,365.0,365.0,NaN,NaN,NaN
AgeStartedOtherFoodbeverage,152.0,126.0,NaN,NaN,NaN
AgeFirstFedMilkdays,365.0,365.0,NaN,NaN,NaN
TypeOfMilkFirstFedWholeMilk,Whole or regular milk,Whole or regular milk,NaN,NaN,NaN
TypeOfMilkFirstFed2Milk,NaN,NaN,NaN,NaN,NaN
TypeOfMilkFirstFed1Milk,NaN,NaN,NaN,NaN,NaN
TypeOfMilkFirstFedFatFreeMilk,NaN,NaN,NaN,NaN,NaN
TypeOfMilkFirstFedSoyMilk,NaN,NaN,NaN,NaN,NaN
TypeOfMilkFirstFedOther,NaN,NaN,NaN,NaN,NaN
HowHealthyIsTheDiet,NaN,NaN,Good,Very good,NaN
Past30DayMilkProductConsumption,Often-once a day or more?,Sometimes-once a week or more but less than on...,Sometimes-once a week or more but less than on...,Never,Never
YouDrinkWholeOrRegularMilk,NaN,NaN,NaN,NaN,NaN
YouDrink2FatMilk,NaN,NaN,NaN,NaN,NaN
YouDrink1FatMilk,12.0,12.0,NaN,NaN,NaN
YouDrinkFatFreeskimMilk,NaN,NaN,NaN,NaN,NaN
YouDrinkSoyMilk,NaN,NaN,NaN,NaN,NaN
YouDrinkAnotherTypeOfMilk,NaN,NaN,30.0,NaN,NaN
RegularMilkUse5TimesPerWeek,NaN,NaN,{My/His/Her} milk drinking has varied over {my...,NaN,NaN
HowOftenDrankMilkAge512,NaN,NaN,Often-once a day or more,NaN,NaN
HowOftenDrankMilkAge1317,NaN,NaN,Sometimes-once a week or more but less than on...,NaN,NaN
HowOftenDrankMilkAge1835,NaN,NaN,Sometimes-once a week or more but less than on...,NaN,NaN
CommunitygovernmentMealsDelivered,NaN,NaN,0.0,NaN,NaN
EatMealsAtCommunityseniorCenter,NaN,NaN,0.0,NaN,NaN
AttendKindergartenThruHighSchool,NaN,NaN,NaN,0.0,1.0
SchoolServesSchoolLunches,NaN,NaN,NaN,NaN,1.0
OfTimesweekGetSchoolLunch,NaN,NaN,NaN,NaN,5.0
SchoolLunchFreeReducedOrFullPrice,NaN,NaN,NaN,NaN,Reduced price
SchoolServeCompleteBreakfastEachDay,NaN,NaN,NaN,NaN,1.0
OfTimesweekGetSchoolBreakfast,NaN,NaN,NaN,NaN,5.0
SchoolBreakfastFreereducedfullPrice,NaN,NaN,NaN,NaN,Reduced price
SummerProgramMealFreereducedPrice,NaN,NaN,NaN,NaN,Did not attend summer program
OfMealsNotHomePrepared,10.0,0.0,5.0,6.0,1.0
OfMealsFromFastFoodOrPizzaPlace,0.0,NaN,0.0,3.0,1.0
OfReadytoeatFoodsInPast30Days,0.0,0.0,0.0,0.0,6.0
OfFrozenMealspizzaInPast30Days,1.0,0.0,0.0,0.0,4.0
HeardOfMyPlate,NaN,NaN,0.0,0.0,NaN
LookedUpMyPlateOnInternet,NaN,NaN,NaN,NaN,NaN
TriedMyPlatePlan,NaN,NaN,NaN,NaN,NaN
MainMealPlannerpreparer,NaN,NaN,1.0,0.0,NaN
SharedMealPlanningpreparingDuty,NaN,NaN,0.0,1.0,NaN
MainFoodShopper,NaN,NaN,1.0,0.0,NaN
SharedFoodShoppingDuty,NaN,NaN,0.0,1.0,NaN
HaveSeriousDifficultyHearing,0.0,0.0,0.0,0.0,0.0
HaveSeriousDifficultySeeing,0.0,0.0,0.0,0.0,0.0
HaveSeriousDifficultyConcentrating,NaN,NaN,0.0,0.0,0.0
HaveSeriousDifficultyWalking,NaN,NaN,0.0,0.0,0.0
HaveDifficultyDressingOrBathing,NaN,NaN,0.0,0.0,0.0
HaveDifficultyDoingErrandsAlone,NaN,NaN,0.0,0.0,NaN
HowOftenDoYouFeelWorriedOrAnxious,NaN,NaN,1.0,0.0,NaN
TakeMedicationForTheseFeelings,NaN,NaN,0.0,0.0,NaN
HowOftenDoYouFeelDepressed,NaN,NaN,1.0,0.0,NaN
TakeMedicationForDepression,NaN,NaN,0.0,0.0,NaN
CoveredByHealthInsurance,1.0,1.0,1.0,1.0,1.0
UsualSleepTimeOnWeekdaysOrWorkdays,NaN,NaN,b'23:00',b'23:30',NaN
UsualWakeTimeOnWeekdaysOrWorkdays,NaN,NaN,b'07:00',b'10:00',NaN
SleepHoursWeekdaysOrWorkdays,NaN,NaN,8.0,10.5,NaN
HowOftenDoYouSnore,NaN,NaN,Occasionally - 3-4 nights a week,Rarely - 1-2 nights a week,NaN
EverToldDoctorHadTroubleSleeping,NaN,NaN,0.0,0.0,NaN
HowOftenFeelOverlySleepyDuringDay,NaN,NaN,Never,Rarely - 1 time a month,NaN
HaveLittleInterestInDoingThings,NaN,NaN,0.0,0.0,NaN
FeelingDownDepressedOrHopeless,NaN,NaN,0.0,0.0,NaN
TroubleSleepingOrSleepingTooMuch,NaN,NaN,0.0,0.0,NaN
FeelingTiredOrHavingLittleEnergy,NaN,NaN,0.0,0.0,NaN
PoorAppetiteOrOvereating,NaN,NaN,0.0,0.0,NaN
FeelingBadAboutYourself,NaN,NaN,0.0,0.0,NaN
TroubleConcentratingOnThings,NaN,NaN,0.0,0.0,NaN
MovingOrSpeakingSlowlyOrTooFast,NaN,NaN,0.0,0.0,NaN
ThoughtYouWouldBeBetterOffDead,NaN,NaN,0.0,0.0,NaN
DifficultyTheseProblemsHaveCaused,NaN,NaN,NaN,NaN,NaN
SmokedTobaccoLast5Days,NaN,NaN,0.0,0.0,0.0
DaysSmokedCigarettesLast5Days,NaN,NaN,NaN,NaN,NaN
CigarettesSmokedPerDay,NaN,NaN,NaN,NaN,NaN
UsedAnyTobaccoProductLast5Days,NaN,NaN,0.0,0.0,0.0
ExperienceConfusionmemoryProblems,NaN,NaN,0.0,NaN,NaN
PhysicalMentalEmotionalLimitations,NaN,NaN,0.0,NaN,NaN
DifficultyManagingMoney,NaN,NaN,No difficulty,NaN,NaN
60SecHr30SecHr2,120.0,114.0,NaN,NaN,NaN
60SecPulse30SecPulse2,NaN,NaN,52.0,82.0,100.0
SystolicBloodPres1StRdgMmHg,NaN,NaN,NaN,112.0,128.0
DiastolicBloodPres1StRdgMmHg,NaN,NaN,NaN,74.0,38.0
SystolicBloodPres2NdRdgMmHg,NaN,NaN,NaN,114.0,128.0
DiastolicBloodPres2NdRdgMmHg,NaN,NaN,NaN,70.0,46.0
SystolicBloodPres3RdRdgMmHg,NaN,NaN,202.0,108.0,128.0
DiastolicBloodPres3RdRdgMmHg,NaN,NaN,62.0,76.0,58.0
EnergyKcal_DR2TOT,NaN,1356.0,1235.0,NaN,1794.0
ProteinGm_DR2TOT,NaN,30.49,38.52,NaN,92.03
CarbohydrateGm_DR2TOT,NaN,229.69,147.49,NaN,153.12
TotalSugarsGm_DR2TOT,NaN,134.37,43.04,NaN,85.81
DietaryFiberGm_DR2TOT,NaN,8.2,13.1,NaN,7.9
TotalFatGm_DR2TOT,NaN,37.02,55.19,NaN,93.98
TotalSaturatedFattyAcidsGm_DR2TOT,NaN,10.368,14.079,NaN,31.098
TotalMonounsaturatedFattyAcidsGm_DR2TOT,NaN,10.443,19.882,NaN,35.405
TotalPolyunsaturatedFattyAcidsGm_DR2TOT,NaN,13.249,17.072,NaN,17.827
CholesterolMg_DR2TOT,NaN,70.0,402.0,NaN,656.0
AlcoholGm_DR2TOT,NaN,0.0,0.0,NaN,0.0
WeightKg,13.7,13.9,79.5,66.3,45.4
RecumbentLengthCm,89.6,95.0,NaN,NaN,NaN
StandingHeightCm,88.6,94.2,158.3,175.7,158.4
BodyMassIndexKgm2,17.5,15.7,31.7,21.5,18.1
WaistCircumferenceCm,48.2,50.0,101.8,79.3,64.1
DirectHdlcholesterolMgdl,NaN,NaN,60.0,47.0,68.0
TotalCholesterolMgdl,NaN,NaN,157.0,148.0,189.0
VigorousWorkActivity,NaN,NaN,0.0,0.0,NaN
ModerateWorkActivity,NaN,NaN,0.0,0.0,NaN
WalkOrBicycle,NaN,NaN,0.0,1.0,NaN
VigorousRecreationalActivities,NaN,NaN,0.0,0.0,NaN
ModerateRecreationalActivities,NaN,NaN,1.0,1.0,NaN
MinutesSedentaryActivity,NaN,NaN,300.0,240.0,NaN
EverBeenToldYouHaveAsthma,0.0,0.0,1.0,0.0,0.0
DoctorEverSaidYouHadArthritis,NaN,NaN,1.0,NaN,NaN
EverToldYouHadHeartAttack,NaN,NaN,0.0,NaN,NaN
AgeWhenToldYouHadHeartAttack,NaN,NaN,NaN,NaN,NaN
EverToldYouHadAStroke,NaN,NaN,0.0,NaN,NaN
AgeWhenToldYouHadAStroke,NaN,NaN,NaN,NaN,NaN
EverToldYouHadCancerOrMalignancy,NaN,NaN,0.0,NaN,NaN
1StCancerWhatKindWasIt,NaN,NaN,NaN,NaN,NaN
Age1StCancerMcq230ADiagnosed,NaN,NaN,NaN,NaN,NaN
EverUsedMarijuanaOrHashish,NaN,NaN,NaN,0.0,NaN
DaysUsedMarijuanaOrHashishmonth,NaN,NaN,NaN,NaN,NaN
EverUsedCocaineheroinmethamphetamine,NaN,NaN,0.0,0.0,NaN
EverUseAnyFormOfCocaine,NaN,NaN,NaN,NaN,NaN
OfDaysUsedCocainemonth,NaN,NaN,NaN,NaN,NaN
EverUsedHeroin,NaN,NaN,NaN,NaN,NaN
OfDaysUsedHeroinmonth,NaN,NaN,NaN,NaN,NaN
EverUsedMethamphetamine,NaN,NaN,NaN,NaN,NaN
DaysUsedMethamphetaminemonth,NaN,NaN,NaN,NaN,NaN
EverBeenInRehabilitationProgram,NaN,NaN,NaN,NaN,NaN
BloodLeadUgdl,NaN,NaN,2.98,0.74,0.39
BloodCadmiumUgl,NaN,0.07,0.24,0.21,0.14
BloodMercuryTotalUgl,NaN,0.47,1.07,10.64,0.2
BloodSeleniumUgl,NaN,142.28,185.71,199.44,179.34
BloodManganeseUgl,NaN,9.41,8.57,14.07,12.6
Gender,Female,Male,Female,Male,Male
AgeInYearsAtScreening,2.0,2.0,66.0,18.0,13.0
AgeInMonthsAtScreening0To24Mos,NaN,NaN,NaN,NaN,NaN
RacehispanicOrigin,Other Race - Including Multi-Racial,Non-Hispanic White,Non-Hispanic Black,Other Race - Including Multi-Racial,Other Race - Including Multi-Racial
RacehispanicOriginWNhAsian,Non-Hispanic Asian,Non-Hispanic White,Non-Hispanic Black,Non-Hispanic Asian,Other Race - Including Multi-Racial
ServedActiveDutyInUsArmedForces,NaN,NaN,0.0,0.0,NaN
EducationLevelChildrenyouth619,NaN,NaN,NaN,More than high school,6th grade
EducationLevelAdults20,NaN,NaN,9-11th grade (Includes 12th grade with no dipl...,NaN,NaN
MaritalStatus,NaN,NaN,Divorced,NaN,NaN
TotalNumberOfPeopleInTheHousehold,5,4,1,5,7 or more people in the Household
TotalNumberOfPeopleInTheFamily,5,4,1,5,7 or more people in the Family
OfChildren5YearsOrYoungerInHh,3 or more,2,0,0,0
OfChildren617YearsOldInHh,0,0,0,0,3 or more
OfAdults60YearsOrOlderInHh,0,0,1,1,0
AnnualHouseholdIncome,100000.0,100000.0,12500.0,NaN,70000.0
AnnualFamilyIncome,100000.0,100000.0,12500.0,NaN,70000.0
RatioOfFamilyIncomeToPoverty,5.0,5.0,0.82,NaN,1.88
TrunkFatG,NaN,NaN,NaN,6358.9,2972.8
TrunkPercentFat,NaN,NaN,NaN,20.9,15.7
TotalPercentFat,NaN,NaN,NaN,22.7,19.0
HowOftenAddSaltToFoodAtTable,NaN,NaN,NaN,Rarely,NaN
OnSpecialDiet,NaN,0.0,0.0,0.0,0.0
WeightLosslowCalorieDiet,NaN,NaN,NaN,NaN,NaN
LowFatlowCholesterolDiet,NaN,NaN,NaN,NaN,NaN
LowSaltlowSodiumDiet,NaN,NaN,NaN,NaN,NaN
DiabeticDiet,NaN,NaN,NaN,NaN,NaN
LowCarbohydrateDiet,NaN,NaN,NaN,NaN,NaN
EnergyKcal_DR1TOT,NaN,1230.0,1202.0,1987.0,1775.0
ProteinGm_DR1TOT,NaN,51.58,20.01,94.19,59.48
CarbohydrateGm_DR1TOT,NaN,160.46,157.45,89.82,188.15
TotalSugarsGm_DR1TOT,NaN,76.97,91.55,14.73,84.22
DietaryFiberGm_DR1TOT,NaN,5.9,8.4,7.1,10.9
TotalFatGm_DR1TOT,NaN,43.24,56.98,137.39,89.18
TotalSaturatedFattyAcidsGm_DR1TOT,NaN,11.372,16.435,35.169,33.252
TotalMonounsaturatedFattyAcidsGm_DR1TOT,NaN,14.333,16.432,45.805,33.712
TotalPolyunsaturatedFattyAcidsGm_DR1TOT,NaN,12.506,19.786,49.873,12.424
CholesterolMg_DR1TOT,NaN,144.0,14.0,462.0,585.0
AlcoholGm_DR1TOT,NaN,0.0,0.0,0.0,0.0
TunaEatenDuringPast30Days,NaN,0.0,NaN,0.0,NaN
DoctorToldYouHaveDiabetes,0,0,0,0,0
AgeWhenFirstToldYouHadDiabetes,NaN,NaN,NaN,NaN,NaN
EverToldYouHavePrediabetes,NaN,NaN,0.0,0.0,0.0
EverToldHaveHealthRiskForDiabetes,NaN,NaN,0.0,0.0,0.0
FamilyHistory,NaN,NaN,NaN,NaN,NaN
TakingInsulinNow,0.0,0.0,0.0,0.0,0.0
TakeDiabeticPillsToLowerBloodSugar,NaN,NaN,NaN,NaN,NaN
WhatWasYourLastA1CLevel,NaN,NaN,NaN,NaN,NaN
Glycohemoglobin,NaN,NaN,6.2,5.2,5.6
SmokedAtLeast100CigarettesInLife,NaN,NaN,1.0,0.0,NaN
AgeStartedSmokingCigarettesRegularly,NaN,NaN,16.0,NaN,NaN
DoYouNowSmokeCigarettes,NaN,NaN,Not at all,NaN,NaN
DaysSmokedCigsDuringPast30Days,NaN,NaN,NaN,NaN,NaN
AvgCigarettesdayDuringPast30Days,NaN,NaN,NaN,NaN,NaN
TriedToQuitSmoking,NaN,NaN,NaN,NaN,NaN
TimesStoppedSmokingCigarettes,NaN,NaN,NaN,NaN,NaN
HowLongWereYouAbleToStopSmoking,NaN,NaN,NaN,NaN,NaN
UnitOfMeasureDayweekmonthyear_2_SMQ,NaN,NaN,NaN,NaN,NaN
CurrentSelfreportedHeightInches,NaN,NaN,63.0,68.0,NaN
CurrentSelfreportedWeightPounds,NaN,NaN,165.0,145.0,NaN
TriedToLoseWeightInPastYear,NaN,NaN,0.0,0.0,NaN
TimesLost10LbsOrMoreToLoseWeight,NaN,NaN,11 times or more,Never,NaN

In [87]:
sleep.shape

(8366, 198)

In [88]:
filtersleep=sleep[(sleep['AgeInYearsAtScreening']>=18) & (sleep['SleepHoursWeekdaysOrWorkdays'].notna())]
sleep=filtersleep

In [89]:
sleep.shape

(5489, 198)

In [ ]:
sample_sleep=np.mean(sleep['SleepHoursWeekdaysOrWorkdays'])
sample_sleep

np.float64(7.62124248496994)

## Part A

In [92]:
rng=np.random.default_rng(seed=51)
k=5000
ninv=1/len(sleep)

bootstrap_sleep=[]
for i in range(k):
    sleep_bootstrap=rng.choice(sleep['SleepHoursWeekdaysOrWorkdays'], size=len(sleep), replace=True)
    ave=sum(sleep_bootstrap)*ninv
    bootstrap_sleep.append(ave)

average_sleep=round(np.mean(bootstrap_sleep),3)

print(f'After {k} bootstraped samples, the average number of hours of sleep is about {average_sleep} with rng seed 51')

After 5000 bootstraped samples, the average number of hours of sleep is about 7.621 with rng seed 51

## Part B

In [94]:
bootstrap_standard_error=np.std(bootstrap_sleep, ddof=1)
bootstrap_standard_error

np.float64(0.022431973114110635)

## Part C

In [95]:
print(f'90% confidence interval [{sample_sleep-1.645*bootstrap_standard_error},{sample_sleep+1.645*bootstrap_standard_error}]')

print(f'95% confidence interval [{sample_sleep-1.96*bootstrap_standard_error},{sample_sleep+1.96*bootstrap_standard_error}]')

print(f'99% confidence interval [{sample_sleep-2.576*bootstrap_standard_error},{sample_sleep+2.576*bootstrap_standard_error}]')

90% confidence interval [7.584341889197228,7.6581430807426525]
95% confidence interval [7.577275817666283,7.665209152273597]
99% confidence interval [7.563457722227991,7.67902724771189]

## Part D

$H_0:\mu=8 \quad H_1:\mu\neq 8 \qquad \alpha=0.1,\quad 0.05,\quad 0.01$

At every level for $\alpha$, we reject the null hypothesis. In each  $(1-\alpha)$ confidence interval, 8 is outside of the interval, so there is enough statistically significant evidence to reject the null. Here, we can claim the true value for average number of hours of sleep on the weekend or workday is less than 8 hours a night.

## Part E

While there is a statistical significance, it is subjective whether the results pose practical significance. Even at 99% confidence, the lower bound for average sleep is above 7.5 so even the worst case has the true value less than half an hour off the prediction. Now, if you're me in the morning, that extra half an hour makes a world of difference, but from a planing perspective, that extra half an hour in the morning might not contribute much.